---

- name: Ensure that git is installed
  apt:
    name: git
  when: ansible_os_family == 'Debian'
  tags: git

- name: Ensure that basic build tools are installed
  apt:
    name: '{{item}}'
  with_items:
  - build-essential
  when: ansible_os_family == 'Debian'

- name: Install python3 dependencies for Mailman 3
  apt:
    name: '{{item}}'
  with_items:
  - python3-dev
  - python3-pip
  - python-dev
  - python-pip
  - python-virtualenv
  when: ansible_os_family == 'Debian'

- name: Ensure that ruby-sass is installed
  apt: name=ruby-sass
  when: ansible_os_family == 'Debian'

- name: Ensure that libpq-dev is installed
  apt: name=libpq-dev
  when: ansible_os_family == 'Debian'

- name: Ensure that pexpect is installed
  pip: name=pexpect

- include: user.yml

#- include: nodenv.yml
#  vars:
#    node_version: 4.4.2
#    nodenv_user: '{{mailman_user}}'
#    nodenv_group: '{{mailman_group}}'
#  tags: node

# Not use depth since GitLab does not support it :-(
- name: clone mailman-bundler
  git:
    repo: https://gitlab.com/mailman/mailman-bundler.git
    dest: /srv/mailman/bundler
    version: '{{mailman_bundler_version|default("HEAD")}}'
  register: cloned_mailman_bundler

- name: change ownership of mailman-bundler
  file:
    path: ~{{mailman_user}}/bundler
    owner: '{{mailman_user}}'
    group: '{{mailman_group}}'
    recurse: yes
  when: cloned_mailman_bundler.changed

- name: Setup a virtualenv for mailman
  command: su - {{mailman_user}} -c "virtualenv {{mailman_path}}/venv"
  args:
    creates: "{{mailman_path}}/venv"

- name: Install buildout for mailman
  pip:
    name: zc.buildout
    virtualenv: '{{mailman_path}}/venv'

- name: Create script directory
  file:
    path:  '{{mailman_path}}/scripts'
    state: directory
    owner: '{{mailman_user}}'
    group: '{{mailman_group}}'
    mode:  0700

- name: copy install.sh
  template:
    src:   install.sh.jinja2
    dest:  '{{mailman_path}}/scripts/install.sh'
    owner: '{{mailman_user}}'
    group: '{{mailman_group}}'
    mode:  0700

- name: copy install_crontab.sh
  template:
    src:   install_crontab.sh.jinja2
    dest:  '{{mailman_path}}/scripts/install_crontab.sh'
    owner: '{{mailman_user}}'
    group: '{{mailman_group}}'
    mode:  0700

- name: copy superuser.sh
  template:
    src:   superuser.sh.jinja2
    dest:  '{{mailman_path}}/scripts/superuser.sh'
    owner: '{{mailman_user}}'
    group: '{{mailman_group}}'
    mode:  0700

- name: copy downgrade_falcon.sh
  template:
    src:   downgrade_falcon.sh.jinja2
    dest:  '{{mailman_path}}/scripts/downgrade_falcon.sh'
    owner: '{{mailman_user}}'
    group: '{{mailman_group}}'
    mode:  0700

- name: Copy buildout config to own file
  copy:
    src:        "{{mailman_path}}/bundler/buildout.cfg"
    dest:       "{{mailman_path}}/bundler/my_buildout.cfg"
    owner:      "{{mailman_user}}"
    group:      "{{mailman_group}}"
    remote_src: True
    force:      no
  register: buildout_copied

- name: Get python3 version
  command: python3 -c 'import sys; v=sys.version_info; print("{major}.{minor}".format(major=v.major, minor=v.minor))'
  register: python3_version
  when: buildout_copied.changed

- name: Set buildout to production mode
  lineinfile:
    dest:   "{{mailman_path}}/bundler/my_buildout.cfg"
    regexp: "^deployment"
    line:   "deployment = production"

- name: Set correct python3 version for buildout
  lineinfile:
    dest:   "{{mailman_path}}/bundler/my_buildout.cfg"
    regexp: "^python3-version"
    line:   "python3-version = {{python3_version.stdout}}"

- name: Run install.sh
  command: su - {{mailman_user}} -c "{{mailman_path}}/scripts/install.sh"
  args:
    creates: "{{mailman_path}}/install.done"

- name: Create log directory for mailman-web
  file:
    path:  "/var/log/mailman-web"
    state: "directory"
    owner: "{{mailman_user}}"
    group: "{{mailman_group}}"
    mode:  "0770"

- name: Copy setting_local.py to right place
  template:
    src:   settings_local.py.jinja2
    dest:  '{{mailman_path}}/bundler/mailman_web/settings_local.py'
    owner: '{{mailman_user}}'
    group: '{{mailman_group}}'
    mode:  0640
  register: settings_copied
  no_log: True

- name: Set site owner in mailman.cfg
  lineinfile:
    dest:   "{{mailman_path}}/bundler/deployment/mailman.cfg"
    regexp: "^site_owner"
    line:   "site_owner = {{mailman_superuser_email}}"

- name: Set the API url in mailman-hyperkitty.cfg
  lineinfile:
    dest:   "{{mailman_path}}/bundler/deployment/mailman-hyperkitty.cfg"
    regexp: "^base_url"
    line:   "base_url = http://localhost:8000/archives"

- name: Set the API key in mailman-hyperkitty.cfg
  lineinfile:
    dest:   "{{mailman_path}}/bundler/deployment/mailman-hyperkitty.cfg"
    regexp: "^api_key"
    line:   "api_key = {{mailman_api_key}}"
  no_log: True

- name: Set user for mailman-web-gunicorn.service
  lineinfile:
    dest:   "{{mailman_path}}/bundler/deployment/mailman-web-gunicorn.service"
    regexp: "User"
    line:   "User={{mailman_web_user}}"

- name: Set group for mailman-web-gunicorn.service
  lineinfile:
    dest:   "{{mailman_path}}/bundler/deployment/mailman-web-gunicorn.service"
    regexp: "Group"
    line:   "Group={{mailman_group}}"

- name: Set ip address in gunicorn.conf
  lineinfile:
    dest:   "{{mailman_path}}/bundler/deployment/gunicorn.conf"
    regexp: "^bind"
    line:   "bind = ['127.0.0.1:8000']"
#    line:   "bind = ['unix:{{mailman_path}}/bundler/var/gunicorn.socket']"

- name: Run downgrade_falcon.sh
  command: su - {{mailman_user}} -c "{{mailman_path}}/scripts/downgrade_falcon.sh"
  args:
    creates: "{{mailman_path}}/downgrade_falcon.done"

#- name: Downgrade falcon to version 0.3
#  pip:
#    name:       "falcon"
#    version:    "0.3"
#    virtualenv: "{{mailman_path}}/bundler/venv-3.4"

#- name: Upgrade mailman to latest version
#  pip: 
#    name:       "mailman"
#    state:    "latest"
#    virtualenv: "{{mailman_path}}/bundler/venv-3.4"

- name: Add destination for mailman
  lineinfile:
    dest:  "/etc/postfix/destinations"
    line:  "{{item}} OK"
    regexp: "^{{item}}"
    insertbefore: "BOF"
  with_items: mailman_domains
  register: dest_file

- name: Run postmap for the destination file
  command: "postmap /etc/postfix/destinations"
  notify: reload postfix
  when: dest_file.changed

- name: Fetch postfix config for mailman
  fetch:
    dest: "/tmp/mailmain_postfix.cfg"
    src:  "{{mailman_path}}/bundler/deployment/postfix-main.cf"
    flat: "yes"

- name: Copy postfix config into main.cf
  blockinfile:
    dest:  "/etc/postfix/main.cf"
    marker:  "## {mark} ANSIBLE MANAGED BLOCK FOR MAILMAN3 ##"
    insertafter: "EOF"
    block: "{{ lookup('file', '/tmp/mailmain_postfix.cfg') }}"

- name: Check if mailman-web log exists
  stat:
    path: "/var/log/mailman-web/mailman-web.log"
  register: mailman_web_log_file

- name: Set correct permissions for log for mailman-web
  file:
    path:  "/var/log/mailman-web/mailman-web.log"
    state: "touch"
    owner: "{{mailman_web_user}}"
    group: "{{mailman_group}}"
    mode:  "0660"
  when: mailman_web_log_file.stat.exists == False

- name: Run post update
  command: su - {{mailman_user}} -c "{{mailman_path}}/bundler/bin/mailman-post-update"
  when: settings_copied.changed

- name: Run install_crontab.sh
  command: su - {{mailman_user}} -c "{{mailman_path}}/scripts/install_crontab.sh"
  args:
    creates: "{{mailman_path}}/install_crontab.done"

- name: Set correct permissions for mailman database
  file:
    path:  "{{mailman_path}}/bundler/var/mailman-web/mailman-web.sqlite"
    state: "file"
    owner: "{{mailman_user}}"
    group: "{{mailman_group}}"
    mode:  "0660"

- name: Create superuser
  expect:
    command: su - {{mailman_user}} -c "{{mailman_path}}/scripts/superuser.sh"
    creates: "{{mailman_path}}/superuser.done"
    responses: 
      Username: "{{mailman_superuser_name}}\n"
      Email:    "{{mailman_superuser_email}}\n"
      Password: "{{mailman_superuser_password}}\n"
  no_log: True

- name: Copy mailman3.service file to systemd dir
  copy:
    src:        "{{mailman_path}}/bundler/deployment/mailman3.service"
    dest:       "/etc/systemd/system/mailman3.service"
    owner:      "root"
    group:      "root"
    remote_src: True
    force:      no
  register: mailman3_service_file

- name: Copy mailman-web-gunicorn.service file to systemd dir
  copy:
    src:        "{{mailman_path}}/bundler/deployment/mailman-web-gunicorn.service"
    dest:       "/etc/systemd/system/mailman-web-gunicorn.service"
    owner:      "root"
    group:      "root"
    remote_src: True
    force:      no
  register: mailman_web_service_file

- name: Run systemctl daemon-reload
  shell: systemctl daemon-reload
  when: mailman3_service_file.changed or mailman_web_service_file.changed

- name: Enable and start mailman3.service
  service:
    name:    "mailman3"
    state:   "started"
    enabled: "yes"

- name: Enable and start mailman-web-gunicorn.service
  service:
    name:    "mailman-web-gunicorn"
    state:   "started"
    enabled: "yes"

